export const nodeSelData = [
  { id: 1, label: 'EGFR', group: 'Protein' },
  { id: 2, label: 'TP53', group: 'Protein' },
  { id: 3, label: 'Glucose', group: 'Metabolites' },
  { id: 4, label: 'ATP', group: 'Metabolites' },
  { id: 5, label: 'Insulin', group: 'Protein' },
  { id: 6, label: 'Pyruvate', group: 'Metabolites' },
  { id: 7, label: 'Obesity', group: 'Phenotypes' },
  { id: 8, label: 'Hypertension', group: 'Phenotypes' },
  { id: 9, label: 'Diabetes', group: 'Disorder' },
  { id: 10, label: 'Cancer', group: 'Disorder' },
  { id: 11, label: 'BRCA1', group: 'Genes' },
  { id: 12, label: 'BRCA2', group: 'Genes' },
  { id: 13, label: 'Albumin', group: 'Protein' },
  { id: 14, label: 'Hemoglobin', group: 'Protein' },
  { id: 15, label: 'Creatinine', group: 'Metabolites' },
  { id: 16, label: 'Lactate', group: 'Metabolites' },
  { id: 17, label: 'Growth Hormone', group: 'Protein' },
  { id: 18, label: 'Cortisol', group: 'Metabolites' },
  { id: 19, label: 'BMI', group: 'Phenotypes' },
  { id: 20, label: 'Cholesterol', group: 'Metabolites' },
  { id: 21, label: 'Arthritis', group: 'Disorder' },
  { id: 22, label: 'Asthma', group: 'Disorder' },
  { id: 23, label: 'APOE', group: 'Genes' },
  { id: 24, label: 'CFTR', group: 'Genes' },
  { id: 25, label: 'Myosin', group: 'Protein' },
  { id: 26, label: 'Fibrinogen', group: 'Protein' },
  { id: 27, label: 'Urea', group: 'Metabolites' },
  { id: 28, label: 'Ammonia', group: 'Metabolites' },
  { id: 29, label: 'Leptin', group: 'Protein' },
  { id: 30, label: 'Adiponectin', group: 'Protein' },
  { id: 31, label: 'Height', group: 'Phenotypes' },
  { id: 32, label: 'Weight', group: 'Phenotypes' },
  { id: 33, label: 'COPD', group: 'Disorder' },
  { id: 34, label: 'Alzheimer\'s Disease', group: 'Disorder' },
  { id: 35, label: 'HLA-A', group: 'Genes' },
  { id: 36, label: 'HLA-B', group: 'Genes' },
  { id: 37, label: 'Troponin', group: 'Protein' },
  { id: 38, label: 'Collagen', group: 'Protein' },
  { id: 39, label: 'Bilirubin', group: 'Metabolites' },
  { id: 40, label: 'Uric Acid', group: 'Metabolites' },
  { id: 41, label: 'Ferritin', group: 'Protein' },
  { id: 42, label: 'Transferrin', group: 'Protein' },
  { id: 43, label: 'Vision', group: 'Phenotypes' },
  { id: 44, label: 'Hearing', group: 'Phenotypes' },
  { id: 45, label: 'Epilepsy', group: 'Disorder' },
  { id: 46, label: 'Parkinson\'s Disease', group: 'Disorder' },
  { id: 47, label: 'TNF', group: 'Genes' },
  { id: 48, label: 'IL6', group: 'Genes' },
  { id: 49, label: 'Keratin', group: 'Protein' },
  { id: 50, label: 'Elastin', group: 'Protein' },
  { id: 51, label: 'Fructose', group: 'Metabolites' },
  { id: 52, label: 'Glycogen', group: 'Metabolites' },
  { id: 53, label: 'IGF-1', group: 'Protein' },
  { id: 54, label: 'Prolactin', group: 'Protein' },
  { id: 55, label: 'Blood Pressure', group: 'Phenotypes' },
  { id: 56, label: 'Heart Rate', group: 'Phenotypes' },
  { id: 57, label: 'Multiple Sclerosis', group: 'Disorder' },
  { id: 58, label: 'Schizophrenia', group: 'Disorder' },
  { id: 59, label: 'MTHFR', group: 'Genes' },
  { id: 60, label: 'P53', group: 'Genes' },
  { id: 61, label: 'Myoglobin', group: 'Protein' },
  { id: 62, label: 'Hemocyanin', group: 'Protein' },
  { id: 63, label: 'Citrate', group: 'Metabolites' },
  { id: 64, label: 'Oxaloacetate', group: 'Metabolites' },
  { id: 65, label: 'Epinephrine', group: 'Metabolites' },
  { id: 66, label: 'Norepinephrine', group: 'Metabolites' },
  { id: 67, label: 'Testosterone', group: 'Metabolites' },
  { id: 68, label: 'Estrogen', group: 'Metabolites' },
  { id: 69, label: 'Osteoporosis', group: 'Disorder' },
  { id: 70, label: 'Gout', group: 'Disorder' },
  { id: 71, label: 'HFE', group: 'Genes' },
  { id: 72, label: 'ACE', group: 'Genes' },
  { id: 73, label: 'CRP', group: 'Protein' },
  { id: 74, label: 'Mucin', group: 'Protein' },
  { id: 75, label: 'Acetylcholine', group: 'Metabolites' },
  { id: 76, label: 'Serotonin', group: 'Metabolites' },
  { id: 77, label: 'Dopamine', group: 'Metabolites' },
  { id: 78, label: 'GABA', group: 'Metabolites' },
  { id: 79, label: 'Skin Color', group: 'Phenotypes' },
  { id: 80, label: 'Hair Color', group: 'Phenotypes' },
  { id: 81, label: 'Psoriasis', group: 'Disorder' },
  { id: 82, label: 'Eczema', group: 'Disorder' },
  { id: 83, label: 'HBB', group: 'Genes' },
  { id: 84, label: 'SOD1', group: 'Genes' },
  { id: 85, label: 'Albumin', group: 'Protein' },
  { id: 86, label: 'Fibrin', group: 'Protein' },
  { id: 87, label: 'Creatine', group: 'Metabolites' },
  { id: 88, label: 'Alanine', group: 'Metabolites' },
  { id: 89, label: 'Renin', group: 'Protein' },
  { id: 90, label: 'Angiotensin', group: 'Protein' },
  { id: 91, label: 'Muscle Mass', group: 'Phenotypes' },
  { id: 92, label: 'Body Fat', group: 'Phenotypes' },
  { id: 93, label: 'Crohn\'s Disease', group: 'Disorder' },
  { id: 94, label: 'Ulcerative Colitis', group: 'Disorder' },
  { id: 95, label: 'APC', group: 'Genes' },
  { id: 96, label: 'KRAS', group: 'Genes' },
  { id: 97, label: 'Thyroxine', group: 'Metabolites' }
  ]

